### ISSUE TITLE
Some eCR QA runs failing

### ISSUE THREAD

**Issue by erick-andrews** [CDCgov/phdi-azure#107]
**Describe the bug**
Not clear if this is supposed to happen w/ the 40 records that I have, but here are the pipelines that errored out:

ed1c3aa0-e52d-11ed-9ada-00155d1d7294
eb200dd0-e52d-11ed-960a-00155d1d7294
e962d69e-e52d-11ed-9f8b-00155d1d7294

**Impact**
Three pipelines were not run. Two errored at verification, one at conversion to fhir.

**To Reproduce**
* upload data from the folder under my name in the patient-data container to the source-data/ecr folder. 

By the way, your instructions all still read sample-data, which is confusing for people trying to upload the data in the right place.

**Expected behavior**
All data should have been uploaded correctly is my assumption, though no overall outcome was provided to us in the email with instructions. I actually don't know the expected outcome.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari
 - Version unknown

**Comment by emmastephenson** [comment]
Next steps: Needs additional research to determine the exact type of error.
May be related to #108.

**Comment by emmastephenson** [comment]
Closing as the FHIR conversion issue and validation errors should be resolved now.
