### ISSUE TITLE
eCR Validation failure encountered on the absence of an optional field

### ISSUE THREAD

**Issue by jazzarran** [CDCgov/phdi-azure#108]
**Describe the problem**
Encounted a validation failure in a message indicating the absence of the 'City' field in the eCR message (which is not a mandatory field per the LADPH interface spec)

**Impact**
Unable to process the eCR message throught the pipeline. In context of UAT testing / no program-business impacts (currently)

**To Reproduce**
1. Send an anonymized eCR message (test/failed message ID: 1c2b788a-36ff-41c3-9be7-13171f205cae_CDA_eICR / pipeline run ID: 9cf47678-e546-11ed-9b86-00155d9996ff)
2. Notice failure in validate_message building block
3. Specific validation failure from DLO:  see Log section below

**Intended outcome**
Message should not have failed validation for the 'City' or any address fields since there are not mandatory per the spec (all addresses i.e. of patient or provider or serving facility).

And note....all of above address fields are present in the message,

**Screenshots**
**NOTE**: Please make sure your screenshots do NOT contain PHI.
![image](https://user-images.githubusercontent.com/10620142/235090198-af5a0d03-18b7-4cd7-83e2-3de83028633a.png)

**Logs**
"validation_results": {
      "fatal": [
        "Could not find field. Field name: 'City' Related elements: Field name: 'addr' Attributes: attribute #1: 'use' with the required value pattern: 'H'"
      ],

**Desktop (please complete the following information):**

**Additional context**
eCR Interface Spec for reference @ https://lacounty.sharepoint.com/:w:/t/USDSPHDIPilot/EeMplhdxLCdAl2IEH5Bb9O8BAmb-a2c7yueZZ4-wjEsHtw?e=mSs4RK

**Comment by jazzarran** [comment]
eCR Interface Spec for reference @ https://lacounty.sharepoint.com/:w:/t/USDSPHDIPilot/EeMplhdxLCdAl2IEH5Bb9O8BAmb-a2c7yueZZ4-wjEsHtw?e=mSs4RK

**Comment by jazzarran** [comment]
Is it an option to log the specific validation failure / reason in ADF level logs. Currently to find the specific details need to navigate to the validation-failures blob container

**Comment by emmastephenson** [comment]
Hopefully fixed with #523.
