### ISSUE TITLE
eCR failures with validation_if_condition errors

### ISSUE THREAD

**Issue by jordan-ahn** [CDCgov/phdi-azure#116]
**Describe the problem**
7 pipeline failures with the same errors. There are two errors per pipeline run: "validation_if_condition" and "Fail1." 

Here are the pipeline run IDs for the failed runs:

8f85e558-e546-11ed-9b86-00155d9996ff
959fb6d0-e546-11ed-9b86-00155d9996ff
962a42a0-e546-11ed-9b86-00155d9996ff
973c7b7c-e546-11ed-9b86-00155d9996ff
99e94c24-e546-11ed-b2a4-00155d9996ff
9a5bee14-e546-11ed-ada2-00155d9996ff
9cf47678-e546-11ed-9b86-00155d9996ff

**Impact**
Unable to process eCR through pipeline.

**To Reproduce**
1. Upload eCR data from /patient-data/ecr-quality-test/jordan
2. Click on failed pipeline line runs
3. Scroll down to Activity runs
4. See errors "validation_if_conditon" and "Fail1"

**Intended outcome**
eCR data would successfully convert to FHIR and upload to FHIR server.

**Screenshots**
Example of one of the failed pipeline runs: 
![image](https://user-images.githubusercontent.com/132096315/235231118-d316a011-beb2-4784-b245-33414da735a4.png)

**Logs**
I went to "validation-failures" container, clicked the file that failed, and went to the "Edit" tab to find these messages. I am not sure if these are the relevant messages but including incase they are helpful. The 7 failures each displayed one of the following:
 
"validation_results": {
"fatal": [
"Could not find field. Field name: 'City' Related elements: Field name: 'addr' Attributes: attribute #1: 'use' with the required value pattern: 'H'"
]

 "validation_results": {
"fatal": [
"Could not find field. Field name: 'City' Related elements: Field name: 'addr' Attributes: attribute #1: 'use' with the required value pattern: 'H'", "Could not find field. Field name: 'Zip'"
],

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 112.0.5615.50

**Comment by jazzarran** [comment]
@jordan-ahn thanks - suspect the issue noticed on https://github.com/CDCgov/phdi-azure/issues/108 might be the same. Will defer to DIBBs team to verify and close one of the tickets (as duplicate) if required.
