### ISSUE TITLE
Failure to convert to FHIR (Error code 2108)

### ISSUE THREAD

**Issue by achang-lac** [CDCgov/phdi-azure#117]
**Describe the bug**
An error (convert_to_fhir) occured from pipeline run using eCR message located in assigned user folder (allene).

**Impact**

With this error, pipeline was only partially finished. At the end of the run, there were only 4 out of 11 activities completed. 
So far, this has affected eCR message: 0ce6e037-927b-4cdf-a680-da9bd1bc47aa, with pipeline run ID: 7823494c-e923-11ed-86bf-00155d5b92bd

**To Reproduce**
1. Upload this message to the pipeline ".../patient-data/ecr-quality-test/allene/0ce6e037-927b-4cdf-a680-da9bd1bc47aa_CDA_eICR" & ".../patient-data/ecr-quality-test/allene/0ce6e037-927b-4cdf-a680-da9bd1bc47aa_CDA_RR"
2. In Azure Data Factory, view this pipeline run and locate "convert_to_fhir" activity. error message by clicking on 
3. Locate "Failed" status in the Activity runs table, and click on the pop-up icon to view error details (code 2108, screenshot provided below)  

**Expected behavior**
Completion of all expected activities from data pipeline without errors. 

**Screenshots**
![image](https://user-images.githubusercontent.com/82547188/235777561-2fa8274d-4082-404c-b0bf-10a7f8f77f57.png)

![image](https://user-images.githubusercontent.com/82547188/235777745-5ba26289-4691-44c8-9934-f5b4bf9046a2.png)

**Logs**
Details section copied from error pop-up is too long to include in this report. Please see the attached text file.
[Error 2108.txt](https://github.com/CDCgov/phdi-azure/files/11377555/Error.2108.txt)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

**Comment by emmastephenson** [comment]
This run from Erik also failed for the same reason: ed1c3aa-e52d-11ed-9ada-00155d1d7294

The ask here is to investigate the FHIR conversion failures and ship a fix for them.
