### ISSUE TITLE
Resolve name standardization error 

### ISSUE THREAD

**Issue by erick-andrews** [CDCgov/phdi-azure#129]
**Describe the bug**
Received a few different errors:
Operation on target standardize_name failed: The payload including configurations on activity/dataSet/linked service is too large. Please check if you have settings with very large value and try to reduce its size.

~Operation on target record_linkage failed: Internal Server Error~ Tracked here: https://app.zenhub.com/workspaces/dibbs-63f7aa3e1ecdbb0011edb299/issues/gh/cdcgov/phdi-azure/129

~Operation on target upload_fhir_bundle failed: {"status_code":"400","message":{"fhir_server_response":{"fhir_server_status_code":400,"fhir_server_response_body":{"resourceType":"OperationOutcome","id":"f827472da5cb831db7e5f9f51481df5d","meta":{"lastUpdated":"2023-05-12T17:37:39.2117319+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"The number of entries in the bundle exceeded the configured limit of 500."}]}}},"bundle":null}~ Tracked here: https://github.com/CDCgov/phdi-azure/issues/130

**Impact**
Some manual triggers of the pipeline did not succeed.

**To Reproduce**
Upload the uat in the patient-data/erick folder.

**Expected behavior**
Should have run successfully, presumably.

**Comment by jordan-ahn** [comment]
I also encountered the record_linkage and upload_fhir_bundle errors. Commenting to avoid duplicate issues.

**Comment by yechana** [comment]
See #131 (record_linkage) and #130 (upload_fhir_bundle). Did not encounter any standardize_name failures.

**Comment by pkchau-skylight** [comment]
Seems like a combo of #130, #131, and #133. I think @emmastephenson also mentioned this during our backlog review earlier today.

**Comment by emmastephenson** [comment]
@erick-andrews to try and find the job ID for the standardize name failure.

The specific ask on this ticket is to investigate the standardize_name issue; the 500+ issue will be investigated in #130.

**Comment by emmastephenson** [comment]
Pipeline execution likely happened around 10:45-11:30am PST on May 12.

**Comment by DanPaseltiner** [comment]
The execution ID for the pipeline run that failed on standardize name is: 5082c4b0-f0eb-11ed-b3fd-00155d9a1382
