### ISSUE TITLE
[Support]: upload_fhir_bundle error - exceeded configured limit of 500

### ISSUE THREAD

**Issue by yechana** [CDCgov/phdi-azure#130]
### Problem

Error at `upload_fhir_bundle` stage, of type "User configuration issue", error code 2108.

Full error message:
`{"status_code":"400","message":{"fhir_server_response":{"fhir_server_status_code":400,"fhir_server_response_body":{"resourceType":"OperationOutcome","id":"74217a745faf80691071af0b3da89801","meta":{"lastUpdated":"2023-05-12T20:44:58.1774511+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"The number of entries in the bundle exceeded the configured limit of 500."}]}}},"bundle":null}`

Affected run IDs:

1. 1a4f97f0-f105-11ed-a37e-00155df253a8

### Impact

The run was not successful

### Steps to Reproduce

1. Rerun the listed run ID

### Intended outcome

The run should not fail

### Desktop

OS: Windows 10
Browser: Chrome
Version 113.0.5672.64

### Review ticket for PHI

- [X] I have reviewed the information in this ticket and can confirm that no PHI has been included.

**Comment by emmastephenson** [comment]
If there are more than 500 resources in a bundle, it will error out. We'll need to split up bundles, but need to make sure the resources referenced in different bundles are grouped together.

**Comment by jordan-ahn** [comment]
Experienced same 2108 "upload_failure_bundle" error in the following run:

1. 1ea9d764-f0e9-11ed-aa96-00155dff47a2

**Comment by emmastephenson** [comment]
Check to see if referential integrity errors are enabled in the Microsoft FHIR server - that will determine next steps forward for fixing this ticket.

**Comment by BradySkylight** [comment]
Good news, I was able to successfully add a 'Condition' resource into the FHIR Server that contained a reference to a 'Patient' resource that did not yet exist.  The transaction type must be 'batch', which allows us to add resources in any order while retaining their references/links even if the referenced resource doesn't yet exist.
