### ISSUE TITLE
[Support]: log_fhir_upload_failure error - fhir_server_response_body doesn't exist

### ISSUE THREAD

**Issue by yechana** [CDCgov/phdi-azure#132]
### Problem

Error at `log_fhir_upload_failure` stage, of type "User configuration issue", error code `InvalidTemplate`.

Full error message:
`The expression 'activity('upload_fhir_bundle').output.fhir_server_response_body' cannot be evaluated because property 'fhir_server_response_body' doesn't exist, available properties are 'status_code, message, bundle, ADFWebActivityResponseHeaders, effectiveIntegrationRuntime, executionDuration, durationInQueue, billingReference'.`

Affected run IDs:

1. 10c310c2-f105-11ed-b68a-00155df253a8
2. 160a618e-f105-11ed-bee5-00155df253a8
3. 1659dd18-f105-11ed-b68a-00155df253a8
4. 1a4f97f0-f105-11ed-a37e-00155df253a8

### Impact

The runs were not successful

### Steps to Reproduce

1. Rerun the listed run IDs

### Intended outcome

The runs should not fail

### Desktop

OS: Windows 10
Browser: Chrome
Version 113.0.5672.64

### Review ticket for PHI

- [X] I have reviewed the information in this ticket and can confirm that no PHI has been included.

**Comment by emmastephenson** [comment]
Correlates to #133. 

When FHIR translation fails, the reason there's no body is because it wasn't able to convert to FHIR.
