### ISSUE TITLE
[Support]: upload_fhir_bundle error - deprecated expression

### ISSUE THREAD

**Issue by yechana** [CDCgov/phdi-azure#133]
### Problem

Error at `upload_fhir_bundle` stage, of type "User configuration issue", error code 2108.

Full error message:
`{"status_code":"400","message":{"fhir_server_response":{"fhir_server_status_code":400,"fhir_server_response_body":{"entry":[{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:24.8614165+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:25.0730574+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:25.1674386+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:25.4569184+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:25.5524343+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:25.7863575+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:25.9008819+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:26.009197+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:26.2645665+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:26.3385308+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:26.428627+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:27.3853915+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:27.4935717+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:28.0818374+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:28.5726567+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:29.1968542+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:30.8259356+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:31.1660876+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:31.2447853+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:31.331347+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:31.8833713+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:32.0845087+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:32.2089778+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:32.3219067+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:32.432565+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:32.8219006+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:33.3167988+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:33.5715246+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:33.6339654+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:35.1040623+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:35.5728806+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:35.8079928+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:36.8858877+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At MedicationStatement.StatusElement.","location":["MedicationStatement.StatusElement // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["MedicationStatement.StatusElement"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:53.150036+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At DiagnosticReport.Code.","location":["DiagnosticReport.Code // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["DiagnosticReport.Code"]},{"severity":"error","code":"invalid","diagnostics":"Element with minimum cardinality 1 cannot be null. At DiagnosticReport.Code.","location":["DiagnosticReport.Code // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["DiagnosticReport.Code"]}]}}},{"response":{"status":"400","outcome":{"resourceType":"OperationOutcome","id":"0cbb877bb4467c5be74c599e4f1601ef","meta":{"lastUpdated":"2023-05-12T20:41:56.3470042+00:00"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Conditional operation on Practitioner was not attempted because search criteria was not selective enough.","location":["ConditionalParameters // OperationOutcome.Location is deprecated, please use OperationOutcome.Expression"],"expression":["ConditionalParameters"]}]}}}],"resourceType":"Bundle","type":"transaction-response"}}},"bundle":null}`

Affected run IDs:

1. 10c310c2-f105-11ed-b68a-00155df253a8

### Impact

The run was not successful

### Steps to Reproduce

1. Rerun the listed run ID

### Intended outcome

The run should not fail

### Desktop

OS: Windows 10
Browser: Chrome
Version 113.0.5672.64

### Review ticket for PHI

- [X] I have reviewed the information in this ticket and can confirm that no PHI has been included.

**Comment by BradySkylight** [comment]
I will take a look, but it appears that we are missing the location for medications.  This will most likely require a minor change int he ECR templates.  I'll be working on this today.
