### ISSUE TITLE
[Support]: UAT convert_to_fhir error 

### ISSUE THREAD

**Issue by achang-lac** [CDCgov/phdi-azure#152]
### Problem

An error (convert_to_fhir) occured for pipeline run using eCR message located in assigned user folder (allene).

This was the only error out of 20 messages, and the Run ID is 7f35e808-f8ef-11ed-b191-00155d0da9cd. Activity ID is 26e449ef-bde4-4cbc-bce2-df1253025f46.

This seems similar to what was described in ticket #117, Failure to convert to FHIR (Error code 2108). 

### Impact

I would consider this error to be severity level 2. While the issue isn't widespread (1 out of 20 messages), impacted message cannot complete the pipeline run.

### Steps to Reproduce

1. Locate Azure Data Factory Studio and launch the studio. 
2. In the left vertical panel, locate the monitor icon (circular shape) to see pipeline runs.
3. Search for affected Run ID, 7f35e808-f8ef-11ed-b191-00155d0da9cd

### Intended outcome

Expected to be able to complete all run steps of the pipeline for this eCR.

### Desktop information

OS [e.g., iOS]: Windows
Browser [e.g., Chrome, Safari]: Chrome
Version [e.g., 22]:

### Attachments

Here's a screenshot of the error pop-up
![GH ticket](https://github.com/CDCgov/phdi-azure/assets/82547188/11ac898d-cd13-4b8d-a1ce-09afc8f22861)

"Details" field copied from error pop-up is saved in this text file
[May23_2108.txt](https://github.com/CDCgov/phdi-azure/files/11548484/May23_2108.txt)

### PHI Review

- [X] I have reviewed the information in this ticket and can confirm that no PHI has been included.

**Comment by pkchau-skylight** [comment]
adding in Dan's comment in Slack for this ticket: "We are pretty sure that we have already implemented a solution for this which will be included in our next release (hopefully tomorrow by EOD). Once the release is available we can pair with some LAC folks to bump your DIBBs version, re-deploy to both dev and uat , and then try re-running the data to confirm that this issue has been resolved."
