### ISSUE TITLE
Extract additional eCR fields currently available in FHIR

### ISSUE THREAD

**Issue by m-goggins** [CDCgov/phdi-azure#175]
**Description**
In order to better understand the impact record linkage has on different patient populations, we need to exptract more data from incoming eCRs, i.e., race/ethnicity.

**Acceptance Criteria**
1. The [message parsing schema](https://github.com/CDCgov/phdi/blob/main/containers/message-parser/app/default_schemas/ecr.json) is updated to include the following fields:
- [x] Gender Identity 
- [x] Race
- [x] Ethnicity 
- [x] DOB

2. The [eCR datastore schema](https://github.com/CDCgov/phdi-azure/blob/main/scripts/Synapse/updateECRDataStore.ipynb) is updated to include the same fields as above.

**Comment by DanPaseltiner** [comment]
Here is the other ticket https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/phdi-azure/188
