### ISSUE TITLE
Add Additional Patient Field to eICR -> FHIR Template

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi-azure#188]
**Description**
The following fields may be included in eICR messages (some only in v3.0 others in both v1.1 and v3.0). If it turns out that this data is available in LAC's data it would allow us make our analysis of eICR data much richer and potentially increase our opportunities to demonstrate the value of eICR and by extension the value of our BBs by making this data accessible. The first step is ensuring that our template for eICR to FHIR conversion covers these fields so that if they are present in messages received by LAC we can extract them.

Additional eICR fields:
- [x] Patient administrative sex - this is what we currently have as 'Gender'
- [x] Patient birth sex 
- [x] Homelessness Status
- [x] Disability Status
- [x] Tribal Affiliation
- [x] Tribal Enrollment Status
- [x] Current Job Title
- [x] Present/Usual Industry
- [x] Present/Usual Occupation
- [x] Preferred Language
- [x] Pregnancy Status

**Acceptance Criteria**
GIVEN an eICR 
WHEN the DIBBs EICR template is used to convert it to FHIR 
THEN all of the fields listed above are included in the resulting FHIR in a manner that complies with the eICR FHIR spec from HL7, if they are present in the eICR.

**Comment by BradySkylight** [comment]
Link to document to map all these items:  

https://docs.google.com/spreadsheets/d/1puur_o_4Fz7gDFA2s8mRZDgFj4V4LhT_a9Cu3cIpE5k/edit#gid=0
