### ISSUE TITLE
Modify analytics notebook to output to file

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi-azure#224]

**Comment by bamader** [comment]
Also as part of this work, make sure the following `if` check gets added to the code in the `link_fhir_record_from_dataset` function:
![Screenshot 2023-07-26 at 5.36.34 PM.png](https://images.zenhubusercontent.com/6007511fbd195723a29aa58b/6642365a-9cb5-4ff1-adc4-5dad32e2eeab)
