### ISSUE TITLE
Profile blocking query generated by DAL to ensure the query is being executed quickly as expected to boost performance

### ISSUE THREAD

**Issue by aathwal3** [CDCgov/phdi-azure#300]
Test the SQL that's being written using DB Vertices Speed - how quickly are we able to return blocks of data

**Comment by BradySkylight** [comment]
Dan and I worked together to profile the queries in PGAdmin against the MPI DB.  We found the queries in their current state to be performant.  There may need to be changes made down the road that can occur in the MPI.py code (make an intersection of the two CTEs and then join that to the overall Patient table).

**Comment by BradySkylight** [comment]
Results:  "[
  {
    ""Plan"": {
      ""Node Type"": ""Nested Loop"",
      ""Parallel Aware"": false,
      ""Async Capable"": false,
      ""Join Type"": ""Inner"",
      ""Actual Rows"": 0,
      ""Actual Loops"": 1,
      ""Inner Unique"": false,
      ""Join Filter"": ""(patient.patient_id = identifier_1.patient_id)"",
      ""Rows Removed by Join Filter"": 0,
      ""Plans"": [
        {
          ""Node Type"": ""Nested Loop"",
          ""Parent Relationship"": ""Outer"",
          ""Parallel Aware"": false,
          ""Async Capable"": false,
          ""Join Type"": ""Left"",
          ""Actual Rows"": 0,
          ""Actual Loops"": 1,
          ""Inner Unique"": true,
          ""Plans"": [
            {
              ""Node Type"": ""Nested Loop"",
              ""Parent Relationship"": ""Outer"",
              ""Parallel Aware"": false,
              ""Async Capable"": false,
              ""Join Type"": ""Left"",
              ""Actual Rows"": 0,
              ""Actual Loops"": 1,
              ""Inner Unique"": false,
              ""Join Filter"": ""(patient.patient_id = address.patient_id)"",
              ""Rows Removed by Join Filter"": 0,
              ""Plans"": [
                {
                  ""Node Type"": ""Nested Loop"",
                  ""Parent Relationship"": ""Outer"",
                  ""Parallel Aware"": false,
                  ""Async Capable"": false,
                  ""Join Type"": ""Left"",
                  ""Actual Rows"": 0,
                  ""Actual Loops"": 1,
                  ""Inner Unique"": false,
                  ""Join Filter"": ""(name.name_id = given_name.name_id)"",
                  ""Rows Removed by Join Filter"": 0,
                  ""Plans"": [
                    {
                      ""Node Type"": ""Nested Loop"",
                      ""Parent Relationship"": ""Outer"",
                      ""Parallel Aware"": false,
                      ""Async Capable"": false,
                      ""Join Type"": ""Left"",
                      ""Actual Rows"": 0,
                      ""Actual Loops"": 1,
                      ""Inner Unique"": false,
                      ""Join Filter"": ""(patient.patient_id = identifier.patient_id)"",
                      ""Rows Removed by Join Filter"": 0,
                      ""Plans"": [
                        {
                          ""Node Type"": ""Hash Join"",
                          ""Parent Relationship"": ""Outer"",
                          ""Parallel Aware"": false,
                          ""Async Capable"": false,
                          ""Join Type"": ""Right"",
                          ""Actual Rows"": 0,
                          ""Actual Loops"": 1,
                          ""Inner Unique"": false,
                          ""Hash Cond"": ""(name.patient_id = patient.patient_id)"",
                          ""Plans"": [
                            {
                              ""Node Type"": ""Seq Scan"",
                              ""Parent Relationship"": ""Outer"",
                              ""Parallel Aware"": false,
                              ""Async Capable"": false,
                              ""Relation Name"": ""name"",
                              ""Alias"": ""name"",
                              ""Actual Rows"": 0,
                              ""Actual Loops"": 0
                            },
                            {
                              ""Node Type"": ""Hash"",
                              ""Parent Relationship"": ""Inner"",
                              ""Parallel Aware"": false,
                              ""Async Capable"": false,
                              ""Actual Rows"": 0,
                              ""Actual Loops"": 1,
                              ""Hash Buckets"": 1024,
                              ""Original Hash Buckets"": 1024,
                              ""Hash Batches"": 1,
                              ""Original Hash Batches"": 1,
                              ""Peak Memory Usage"": 8,
                              ""Plans"": [
                                {
                                  ""Node Type"": ""Nested Loop"",
                                  ""Parent Relationship"": ""Outer"",
                                  ""Parallel Aware"": false,
                                  ""Async Capable"": false,
                                  ""Join Type"": ""Inner"",
                                  ""Actual Rows"": 0,
                                  ""Actual Loops"": 1,
                                  ""Inner Unique"": true,
                                  ""Plans"": [
                                    {
                                      ""Node Type"": ""Seq Scan"",
                                      ""Parent Relationship"": ""Outer"",
                                      ""Parallel Aware"": false,
                                      ""Async Capable"": false,
                                      ""Relation Name"": ""address"",
                                      ""Alias"": ""address_1"",
                                      ""Actual Rows"": 0,
                                      ""Actual Loops"": 1,
                                      ""Filter"": ""(\""left\""((line_1)::text, 4) = '123 '::text)"",
                                      ""Rows Removed by Filter"": 6
                                    },
                                    {
                                      ""Node Type"": ""Index Scan"",
                                      ""Parent Relationship"": ""Inner"",
                                      ""Parallel Aware"": false,
                                      ""Async Capable"": false,
                                      ""Scan Direction"": ""Forward"",
                                      ""Index Name"": ""patient_pkey"",
                                      ""Relation Name"": ""patient"",
                                      ""Alias"": ""patient"",
                                      ""Actual Rows"": 0,
                                      ""Actual Loops"": 0,
                                      ""Index Cond"": ""(patient_id = address_1.patient_id)"",
                                      ""Rows Removed by Index Recheck"": 0
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        },
                        {
                          ""Node Type"": ""Seq Scan"",
                          ""Parent Relationship"": ""Inner"",
                          ""Parallel Aware"": false,
                          ""Async Capable"": false,
                          ""Relation Name"": ""identifier"",
                          ""Alias"": ""identifier"",
                          ""Actual Rows"": 0,
                          ""Actual Loops"": 0,
                          ""Filter"": ""((type_code)::text = 'MR'::text)"",
                          ""Rows Removed by Filter"": 0
                        }
                      ]
                    },
                    {
                      ""Node Type"": ""Seq Scan"",
                      ""Parent Relationship"": ""Inner"",
                      ""Parallel Aware"": false,
                      ""Async Capable"": false,
                      ""Relation Name"": ""given_name"",
                      ""Alias"": ""given_name"",
                      ""Actual Rows"": 0,
                      ""Actual Loops"": 0,
                      ""Filter"": ""(given_name_index = 0)"",
                      ""Rows Removed by Filter"": 0
                    }
                  ]
                },
                {
                  ""Node Type"": ""Seq Scan"",
                  ""Parent Relationship"": ""Inner"",
                  ""Parallel Aware"": false,
                  ""Async Capable"": false,
                  ""Relation Name"": ""address"",
                  ""Alias"": ""address"",
                  ""Actual Rows"": 0,
                  ""Actual Loops"": 0
                }
              ]
            },
            {
              ""Node Type"": ""Index Only Scan"",
              ""Parent Relationship"": ""Inner"",
              ""Parallel Aware"": false,
              ""Async Capable"": false,
              ""Scan Direction"": ""Forward"",
              ""Index Name"": ""person_pkey"",
              ""Relation Name"": ""person"",
              ""Alias"": ""person"",
              ""Actual Rows"": 0,
              ""Actual Loops"": 0,
              ""Index Cond"": ""(person_id = patient.person_id)"",
              ""Rows Removed by Index Recheck"": 0,
              ""Heap Fetches"": 0
            }
          ]
        },
        {
          ""Node Type"": ""Seq Scan"",
          ""Parent Relationship"": ""Inner"",
          ""Parallel Aware"": false,
          ""Async Capable"": false,
          ""Relation Name"": ""identifier"",
          ""Alias"": ""identifier_1"",
          ""Actual Rows"": 0,
          ""Actual Loops"": 0,
          ""Filter"": ""(((type_code)::text = 'MR'::text) AND (\""right\""((patient_identifier)::text, 4) = 'john'::text))"",
          ""Rows Removed by Filter"": 0
        }
      ]
    },
    ""Triggers"": [
    ]
  }
]"

**Comment by BradySkylight** [comment]
#	Node	Rows	Loops
Actual
1.	 Nested Loop Inner Join (rows=0 loops=1)
Join Filter: (patient.patient_id = identifier_1.patient_id)
0	1
2.	 Nested Loop Left Join (rows=0 loops=1)	0	1
3.	 Nested Loop Left Join (rows=0 loops=1)
Join Filter: (patient.patient_id = address.patient_id)
0	1
4.	 Nested Loop Left Join (rows=0 loops=1)
Join Filter: (name.name_id = given_name.name_id)
0	1
5.	 Nested Loop Left Join (rows=0 loops=1)
Join Filter: (patient.patient_id = identifier.patient_id)
0	1
6.	 Hash Right Join (rows=0 loops=1)
Hash Cond: (name.patient_id = patient.patient_id)
0	1
7.	 Seq Scan on name as name (rows=0 loops=0)	0	0
8.	 Hash (rows=0 loops=1)
Buckets: 1024 Batches: 1 Memory Usage: 8 kB
0	1
9.	 Nested Loop Inner Join (rows=0 loops=1)	0	1
10.	 Seq Scan on address as address_1 (rows=0 loops=1)
Filter: ("left"((line_1)::text, 4) = '123 '::text)
Rows Removed by Filter: 6
0	1
11.	 Index Scan using patient_pkey on patient as patient (rows=0 loops=0)
Index Cond: (patient_id = address_1.patient_id)
0	0
12.	 Seq Scan on identifier as identifier (rows=0 loops=0)
Filter: ((type_code)::text = 'MR'::text)
Rows Removed by Filter: 0
0	0
13.	 Seq Scan on given_name as given_name (rows=0 loops=0)
Filter: (given_name_index = 0)
Rows Removed by Filter: 0
0	0
14.	 Seq Scan on address as address (rows=0 loops=0)	0	0
15.	 Index Only Scan using person_pkey on person as person (rows=0 loops=0)
Index Cond: (person_id = patient.person_id)
0	0
16.	 Seq Scan on identifier as identifier_1 (rows=0 loops=0)
Filter: (((type_code)::text = 'MR'::text) AND ("right"((patient_identifier)::text, 4) = 'john'::text))
Rows Removed by Filter: 0
0	0
Total rows: 1 of 1
Query complete 00:00:00.099
Ln 3, Col 48

**Comment by BradySkylight** [comment]
Query 2 Results:

	#	Node	Rows	Loops
Actual
1.	 Nested Loop Inner Join (rows=0 loops=1)
Join Filter: (patient.patient_id = name_2.patient_id)
0	1
2.	 Nested Loop Left Join (rows=0 loops=1)	0	1
3.	 Nested Loop Left Join (rows=0 loops=1)
Join Filter: (patient.patient_id = address.patient_id)
0	1
17.	 Index Only Scan using person_pkey on person as person (rows=0 loops=0)
Index Cond: (person_id = patient.person_id)
0	0
18.	 Seq Scan on name as name_2 (rows=0 loops=0)
Filter: ("left"((last_name)::text, 4) = 'thom'::text)
Rows Removed by Filter: 0
0	0
Total rows: 1 of 1
Query complete 00:00:00.218
Ln 56, Col 13

**Comment by BradySkylight** [comment]
Query 2 Results:

	#	Node	Rows	Loops
Actual
1.	 Nested Loop Inner Join (rows=0 loops=1)
Join Filter: (patient.patient_id = name_2.patient_id)
0	1
2.	 Nested Loop Left Join (rows=0 loops=1)	0	1
3.	 Nested Loop Left Join (rows=0 loops=1)
Join Filter: (patient.patient_id = address.patient_id)
0	1
17.	 Index Only Scan using person_pkey on person as person (rows=0 loops=0)
Index Cond: (person_id = patient.person_id)
0	0
18.	 Seq Scan on name as name_2 (rows=0 loops=0)
Filter: ("left"((last_name)::text, 4) = 'thom'::text)
Rows Removed by Filter: 0
0	0
Total rows: 1 of 1
Query complete 00:00:00.218
Ln 56, Col 13

**Comment by BradySkylight** [comment]
Query 2:

**Comment by BradySkylight** [comment]
Query 2:
