### ISSUE TITLE
Extract SQL generated by SQLAlchemy for blocking

### ISSUE THREAD

**Issue by aathwal3** [CDCgov/phdi-azure#302]

**Comment by BradySkylight** [comment]
This is done.  Query 1 and Query 2 below

**Comment by BradySkylight** [comment]
Query 2:

WITH given_name_cte AS (
    SELECT
        name.patient_id AS patient_id
    FROM
        name
        JOIN (
            SELECT
                given_name.given_name_id AS given_name_id,
                given_name.name_id AS name_id,
                given_name.given_name AS given_name,
                given_name.given_name_index AS given_name_index
            FROM
                given_name
            WHERE
                LEFT(given_name.given_name, 4) = :given_name_1
        ) AS given_name_cte_subq ON name.name_id = given_name_cte_subq.name_id
    WHERE
        name.name_id = given_name_cte_subq.name_id
),
name_cte AS (
    SELECT
        name.patient_id AS patient_id
    FROM
        name
    WHERE
        LEFT(name.last_name, 4) = :last_name_1
)
SELECT
    patient.patient_id,
    person.person_id,
    patient.dob AS birthdate,
    patient.sex,
    ident_subq.mrn,
    name.last_name,
    gname_subq.given_name AS first_name,
    address.line_1 AS address,
    address.zip_code AS zip,
    address.city,
    address.state
FROM
    patient
    LEFT OUTER JOIN (
        SELECT
            identifier.patient_identifier AS mrn,
            identifier.patient_id AS patient_id
        FROM
            identifier
        WHERE
            identifier.type_code = :type_code_1
    ) AS ident_subq ON patient.patient_id = ident_subq.patient_id
    LEFT OUTER JOIN name ON patient.patient_id = name.patient_id
    LEFT OUTER JOIN (
        SELECT
            given_name.given_name AS given_name,
            given_name.name_id AS name_id
        FROM
            given_name
        WHERE
            given_name.given_name_index = :given_name_index_1
    ) AS gname_subq ON name.name_id = gname_subq.name_id
    LEFT OUTER JOIN address ON patient.patient_id = address.patient_id
    LEFT OUTER JOIN person ON person.person_id = patient.person_id
    JOIN given_name_cte ON given_name_cte.patient_id = patient.patient_id
    JOIN name_cte ON name_cte.patient_id = patient.patient_id

**Comment by BradySkylight** [comment]
Query 1:

WITH identifier_cte AS (
        SELECT
            identifier.patient_id AS patient_id
        FROM
            identifier
        WHERE
            RIGHT(identifier.patient_identifier, 4) = :pat_id_4
            AND identifier.type_code = 'MR'
    ),
    address_cte AS (
        SELECT
            address.patient_id AS patient_id
        FROM
            address
        WHERE
            LEFT(address.line_1, 4) = :addr_line1_4
    )
SELECT
    patient.patient_id,
    person.person_id,
    patient.dob AS birthdate,
    patient.sex,
    ident_subq.mrn,
    name.last_name,
    gname_subq.given_name AS first_name,
    address.line_1 AS address,
    address.zip_code AS zip,
    address.city,
    address.state
FROM
    patient
    LEFT OUTER JOIN (
        SELECT
            identifier.patient_identifier AS mrn,
            identifier.patient_id AS patient_id
        FROM
            identifier
        WHERE
            identifier.type_code = :type_code_1
    ) AS ident_subq ON patient.patient_id = ident_subq.patient_id
    LEFT OUTER JOIN name ON patient.patient_id = name.patient_id
    LEFT OUTER JOIN (
        SELECT
            given_name.given_name AS given_name,
            given_name.name_id AS name_id
        FROM
            given_name
        WHERE
            given_name.given_name_index = :given_name_index_1
    ) AS gname_subq ON name.name_id = gname_subq.name_id
    LEFT OUTER JOIN address ON patient.patient_id = address.patient_id
    LEFT OUTER JOIN person ON person.person_id = patient.person_id
    JOIN identifier_cte ON identifier_cte.patient_id = patient.patient_id
    JOIN address_cte ON address_cte.patient_id = patient.patient_id
