### ISSUE TITLE
Update Message Parser to return data types other than strings

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi-azure#306]
Description

Currently, for each field that it parsers the message parsers returns either null value, or a string. We convert all values to strings so that in the event that multiple values are returned for a given FHIRpath they can returned as a single comma delimited string. This is a problem for numeric values, in particular quantitative lab results, because this data should not be represented as a string and results in parsing problems down stream when building the eCR datastore.

This logic is currently applied in two places:

1. [message-parser/app/main.py lines 187-190](https://github.com/CDCgov/phdi/blob/main/containers/message-parser/app/main.py#L187-L190)
2.  [message-parser/app/main.py lines 200-205](https://github.com/CDCgov/phdi/blob/main/containers/message-parser/app/main.py#L200-L205)

To address this problem we should first refactor this logic into a single function that accepts a list and returns a single value can be called in these two locations. Then we should expand the function so that when a list with a single element is supplied it returns just that value with NO type conversion. This will mean that in the event that a single numeric value is encountered then the message parser will return a number and not a string for that value in the parsing schema.

Acceptance Criteria:

GIVEN a new help function for coalescing the value(s) parsed from FHIR into a single value to return to the user
WHEN the function is called with an empty list
THEN `None` is returned

GIVEN a new help function for coalescing the value(s) parsed from FHIR into a single value to return to the user
WHEN the function is called with a list containing only a single value
THEN that value is return with no additional transformations

GIVEN a new help function for coalescing the value(s) parsed from FHIR into a single value to return to the user
WHEN the function is called with a list containing multiple values
THEN all values are converted strings and they are returned as single comma delimited string

GIVEN the `/message_parser`
WHEN the parse-message endpoint is called 
THEN all numeric values that are extracted are returned as numbers and NOT strings

**Comment by aathwal3** [comment]
Blocked for now - dont want to depoly to LAC
