### ISSUE TITLE
Investigate ELR pipeline errors (in UAT) with named contact from LAC 

### ISSUE THREAD

**Issue by aathwal3** [CDCgov/phdi-azure#319]

**Comment by nickclyde** [comment]
The errors all seem to have to do with incorrectly formatted date strings:
`The format of Date or DateTime is invalid: 20230820185501-080000000.`

This has 5 extra zeroes after a valid datetime string. We inspected a failed ELR message, and it contained a number of correctly formatted datetimes alongside this incorrect one with five extra zeroes.
