### ISSUE TITLE
Implement the health check endpoint

### ISSUE THREAD

**Issue by DanPaseltiner** [CDCgov/phdi-azure#372]
When a client issues a GET request to the root endpoint `hostname/` of the standardization service, assuming the service is up and running properly, they should receive an HTTP `200` and a JSON object in the response body that matches `{status: 'Ok'}`. This behavior should match all other DIBBs services.

**Comment by robertmitchellv** [comment]
This was implemented in this PR: https://github.com/CDCgov/phdi/pull/982
